apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 {{- if lower .Values.sename}}
 name: ingress-router-{{ lower .Values.sename }}
 {{- else }}
 name: ingress-router
 {{- end }}
 annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /{{ lower .Values.sename }}
        pathType: prefix
        backend:
          service:
            name: payment-service-{{ lower .Values.sename }}-svc
            port:
              number: 8080
